### ISSUE TITLE
Rounded Track Problem

### ISSUE THREAD

**Issue by gevv** [cdhigh/sprintFont#1]
Hello,

Some track are not rounded. 

![Untitled 1](https://user-images.githubusercontent.com/5096676/181727794-1ad9f839-89b0-4887-afb2-05617328be8b.png)

![Untitled 3](https://user-images.githubusercontent.com/5096676/181727972-09fe07d8-48fa-4e2e-b8da-795447996726.png)

when i repeat it i get an error message

![Untitled 2](https://user-images.githubusercontent.com/5096676/181727825-2b6e72ce-4c9d-4421-9670-6c28d3ac6af0.png)

**Comment by cdhigh** [comment]
![181727972-09fe07d8-48fa-4e2e-b8da-795447996726](https://user-images.githubusercontent.com/2580077/181757739-d161ef65-03e0-40d5-a869-f75b4a4a1b12.png)

The distance "D" isn't enough to draw a arc.
try to decrease the param 'd'.

**Comment by gevv** [comment]
Hello
[bike-simple-pcb-file.zip](https://github.com/cdhigh/sprintFont/files/9276984/bike-simple-pcb-file.zip)
,  I tried it didn't work I guess the drawing is not suitable

**Comment by cdhigh** [comment]
Release v1.5.1, add two distances for tangent arc. can solve your problem.

**Comment by gevv** [comment]
Thanks @cdhigh works very well.

Best regards
