### ISSUE TITLE
3D View?

### ISSUE THREAD

**Issue by gevv** [cdhigh/sprintFont#2]
Hello, is it possible to add 3D view feature with the of additional program?

sample; 
https://youtu.be/hBfg1xFrojA 
https://youtu.be/6gGSLg_eYoA

Thanks.

**Comment by cdhigh** [comment]
It's next to impossible, Sprint-Layout has no footprint (macro is not footprint), the macro's name is missing after it been placed in board.
Sprint-Layout is a light-weight software only, it has a lot of limits. (but I still like it~)

**Comment by gevv** [comment]
Hello, Understood thanks @cdhigh
